name: Update README stats

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Readme Stats
        run: |
          curl -o ./readme-stats.png "https://github-readme-stats.vercel.app/api/top-langs/?username=lucasNacif&layout=compact&hide=css,html,Handlebars&theme=radical&cache_seconds=0&token=${{ secrets.GH_TOKEN }}"

      - name: Commit updated stats
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add readme-stats.png
          git commit -m "Update README stats" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
